language: php

os:
    - linux

php:
    - 7.3

before_script:
    - chmod 777 -R storage
    - cp .env.travis .env
    - composer install --no-interaction
    - composer self-update
    - php artisan key:generate
    - php artisan migrate
    - php artisan passport:keys
    - nvm install node
    - npm install --global cross-env
    - npm run production

script:
    - vendor/bin/phpunit

services:
    - redis-server

cache:
    directories:
        - vendor
env:
    LANGUAGE=de
