language: php

os:
    - linux

php: 
    - 7.3
    
before_script:
    - mkdir storage/framework/views
    - chmod 777 -R storage
    - cp .env.travis .env
    - composer self-update
    - composer install --no-interaction
    - php artisan key:generate
    - php artisan migrate
    - php artisan passport:keys
    
script:
    - vendor/bin/phpunit
 
services:
    - redis-server
    
cache:
    directories:
        - vendor